before_install: gem install bundler

env:
  global:
    - CC_TEST_REPORTER_ID=6552c01f21ef50e3d3f9b53590a30b51bc45fa5ae678145987a3aec2935e306e

language: ruby
rvm:
  - 2.5
  - 2.4.3
  - 2.4.2
  - 2.4.1
  - 2.4.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT